language: node_js
sudo: false
node_js:
- node
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- rvm install 2.x
- gem update --system
- gem install sass
- gem install compass
install:
- npm install
- npm install -g bower grunt-cli karma
- bower install
- npm install grunt-sass
- npm install archiver --save
- npm install grunt-contrib-watch --save-dev
- npm install grunt-contrib-sass --save-dev
- npm install grunt-contrib-cssmin --save-dev
- npm install grunt-contrib-compress --save-dev
- npm install grunt-contrib-copy --save-dev
- npm install grunt-contrib-jshint --save-dev
- npm install grunt-contrib-uglify --save-dev
- npm install grunt-contrib-clean --save-dev
script:
- grunt build --verbose
deploy:
  provider: releases
  api_key:
    secure: gKfaPXGT8BhH6MhSBjCOAUfJOS8/kgIRzTTq07hQNmMXIVc4HHhfthmurH8W/v08ooocpCOcDxnt7szoTLLOz+7+0uMYvZXgk7tba82sfNvewsvv6U06BUI2Dxr5jsAmxMo2UFsdD+Wc3ioxR7XdWtBaoxF9EMLW27MMrTc0L+o=
  file: target/tpl_bodenleger-stockach.zip
  skip_cleanup: true
on:
  tags: true
